spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recruitmentsvc
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.format_sql: true
  flyway:
    locations: classpath:db/migration
server:
  port: 8080

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000
